version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gymGuardianDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
